[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Johto Mom taking a fraction of payout
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if total_cashout_rows > 7 then"
position = "before"
payload = '''
local johto_moms = find_joker('johto_mom')
--for i = 1, #johto_moms do
for i, v in ipairs(SMODS.find_card("j_marcpoke_johto_mom")) do
  local moms_cut = v.ability.extra.tax_rate * dollars
  add_round_eval_row({bonus = true, name='joker_johto_mom'..i, pitch = pitch, dollars = -moms_cut, card = v})
  v.config.center:add_to_savings(v, moms_cut * v.ability.extra.efficiency)
  dollars = dollars - moms_cut
end
'''
match_indent = true