[manifest]
version = "1.0.0"
dump_lua = true
priority = 10

#Add efficiency to the variables that get improved by energy
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "functions/energyfunctions.lua"]'
pattern = 'energy_max = 3'
position = "before"
payload = 'energy_values.efficiency = .1'
match_indent = true