[manifest]
version = "1.0.0"
dump_lua = true
priority = 10

#Toxtricity effect... for vanilla jokers?
#[[patches]]
#[patches.pattern]
#target = '=[SMODS Pokermon "functions/energyfunctions.lua"]'
#pattern = "if increase then"
#position = "after"
#payload = '''
#    print(#SMODS.find_card("j_marcpoke_toxtricity"))
#    print("inc", increase, increase/2)
#    increase = increase + (increase / 2) * (#SMODS.find_card("j_marcpoke_toxtricity"))
#'''
#match_indent = true#

#Toxtricity effect for pokemon
#[[patches]]
#[patches.pattern]
#target = '=[SMODS Pokermon "functions/energyfunctions.lua"]'
#
#pattern = "local bonus_amt = math.ceil(card.ability.extra[field]/(increased and 2 or 1))"
#position = "after"
#payload = '''
#    print(#SMODS.find_card("j_marcpoke_toxtricity"))
#    print("inc", increase, increase/2)
#    bonus_amt = bonus_amt + (bonus_amt / 2) * (#SMODS.find_card("j_marcpoke_toxtricity"))
#'''
#match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "functions/energyfunctions.lua"]'
pattern = "local addition = energy_values[name]"
position = "after"
payload = 'addition = addition + (addition / 2) * (#SMODS.find_card("j_marcpoke_toxtricity_amped"))'
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "local dissolve_time = 0.7*(dissolve_time_fac or 1)"
position = "before"
payload = '''
if G and G.jokers then
    for i, v in ipairs(G.jokers.cards) do
        if v and v.config and v.config.center and v ~= self then
            if v.config.center.joker_destroyed_effect then
                v.config.center.joker_destroyed_effect(v, v)
            end
        end
    end
end
'''
match_indent = true

#G.E_MANAGER:add_event(Event({
#    func = function()
#        for i, v in G.jokers.cards do
#            v.calculate(v, self, {joker_destroyed = true})
#        end
#    end
#}))
